version: "3.8"

services:
  # Base de données MariaDB locale pour le stockage des données
  db-silver-happy:
    image: mariadb:10.11
    container_name: db-silver-happy
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=Europe/Paris
    volumes:
      - ./mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-p${DB_ROOT_PASS}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - silver-happy-net

  # Application Frontend (Web) construite localement avec montage du code pour le développement
  web-silver-happy:
    build: ./web
    container_name: web-silver-happy
    restart: unless-stopped
    depends_on:
      db-silver-happy:
        condition: service_healthy
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - DB_HOST=db-silver-happy
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    networks:
      - silver-happy-net

  # Backend API en Go construit localement et exécuté via 'go run' (mode développement)
  api-silver-happy:
    build: ./api
    container_name: api-silver-happy
    restart: unless-stopped
    depends_on:
      db-silver-happy:
        condition: service_healthy
    ports:
      - "8082:8082"
    volumes:
      - ./api:/api
    command: go run .
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8082/",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - .env
    networks:
      - silver-happy-net

  # Interface graphique d'administration pour la base de données (phpMyAdmin)
  pma-silver-happy:
    image: phpmyadmin:latest
    container_name: pma-silver-happy
    restart: unless-stopped
    depends_on:
      db-silver-happy:
        condition: service_healthy
    ports:
      - "8081:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - PMA_HOST=db-silver-happy
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    networks:
      - silver-happy-net

networks:
  silver-happy-net:
    driver: bridge